In [1]:
import wrds
import pandas as pd
import numpy as np
import yaml
from datetime import datetime
from pathlib import Path

In [2]:
# Read username from config file
file_path = Path.cwd() / '..' / 'config' / 'credentials.yaml'
with open(file_path, 'r') as file:
    cred = yaml.safe_load(file)
username = cred['wrds']['username']

db = wrds.Connection(wrds_username=username)

Loading library list...
Done

In [3]:
print(db.list_tables(library='optionm'))

['borrate1996', 'borrate1997', 'borrate1998', 'borrate1999', 'borrate2000', 'borrate2001', 'borrate2002', 'borrate2003', 'borrate2004', 'borrate2005', 'borrate2006', 'borrate2007', 'borrate2008', 'borrate2009', 'borrate2010', 'borrate2011', 'borrate2012', 'borrate2013', 'borrate2014', 'borrate2015', 'borrate2016', 'borrate2017', 'borrate2018', 'borrate2019', 'borrate2020', 'borrate2021', 'borrate2022', 'borrate2023', 'borrate2024', 'borrate2025', 'country', 'currency', 'distrd', 'distribution', 'distribution_projection', 'distrprojd1996', 'distrprojd1997', 'distrprojd1998', 'distrprojd1999', 'distrprojd2000', 'distrprojd2001', 'distrprojd2002', 'distrprojd2003', 'distrprojd2004', 'distrprojd2005', 'distrprojd2006', 'distrprojd2007', 'distrprojd2008', 'distrprojd2009', 'distrprojd2010', 'distrprojd2011', 'distrprojd2012', 'distrprojd2013', 'distrprojd2014', 'distrprojd2015', 'distrprojd2016', 'distrprojd2017', 'distrprojd2018', 'distrprojd2019', 'distrprojd2020', 'distrprojd2021', 'distrprojd2022', 'distrprojd2023', 'exchange', 'exchgd', 'forward_price', 'futures', 'futures_price', 'fwdprd1996', 'fwdprd1997', 'fwdprd1998', 'fwdprd1999', 'fwdprd2000', 'fwdprd2001', 'fwdprd2002', 'fwdprd2003', 'fwdprd2004', 'fwdprd2005', 'fwdprd2006', 'fwdprd2007', 'fwdprd2008', 'fwdprd2009', 'fwdprd2010', 'fwdprd2011', 'fwdprd2012', 'fwdprd2013', 'fwdprd2014', 'fwdprd2015', 'fwdprd2016', 'fwdprd2017', 'fwdprd2018', 'fwdprd2019', 'fwdprd2020', 'fwdprd2021', 'fwdprd2022', 'fwdprd2023', 'fwdprd2024', 'fwdprd2025', 'historical_volatility', 'hvold1996', 'hvold1997', 'hvold1998', 'hvold1999', 'hvold2000', 'hvold2001', 'hvold2002', 'hvold2003', 'hvold2004', 'hvold2005', 'hvold2006', 'hvold2007', 'hvold2008', 'hvold2009', 'hvold2010', 'hvold2011', 'hvold2012', 'hvold2013', 'hvold2014', 'hvold2015', 'hvold2016', 'hvold2017', 'hvold2018', 'hvold2019', 'hvold2020', 'hvold2021', 'hvold2022', 'hvold2023', 'hvold2024', 'hvold2025', 'idxdvd', 'index_dividend', 'indexd', 'op_view', 'op_view_tick', 'opinfd', 'opprcd1996', 'opprcd1997', 'opprcd1998', 'opprcd1999', 'opprcd2000', 'opprcd2001', 'opprcd2002', 'opprcd2003', 'opprcd2004', 'opprcd2005', 'opprcd2006', 'opprcd2007', 'opprcd2008', 'opprcd2009', 'opprcd2010', 'opprcd2011', 'opprcd2012', 'opprcd2013', 'opprcd2014', 'opprcd2015', 'opprcd2016', 'opprcd2017', 'opprcd2018', 'opprcd2019', 'opprcd2020', 'opprcd2021', 'opprcd2022', 'opprcd2023', 'opprcd2024', 'opprcd2025', 'option', 'option_history', 'option_price_2002', 'option_price_2003', 'option_price_2004', 'option_price_2005', 'option_price_2006', 'option_price_2007', 'option_price_2008', 'option_price_2009', 'option_price_2010', 'option_price_2011', 'option_price_2012', 'option_price_2013', 'option_price_2014', 'option_price_2015', 'option_price_2016', 'option_price_2017', 'option_price_2018', 'option_price_2019', 'option_price_2020', 'option_price_2021', 'option_price_2022', 'option_price_2023', 'option_price_view', 'optionmeurnames', 'optionmnames', 'opvold', 'release', 'rollover', 'secnmd', 'secprd', 'secprd1996', 'secprd1997', 'secprd1998', 'secprd1999', 'secprd2000', 'secprd2001', 'secprd2002', 'secprd2003', 'secprd2004', 'secprd2005', 'secprd2006', 'secprd2007', 'secprd2008', 'secprd2009', 'secprd2010', 'secprd2011', 'secprd2012', 'secprd2013', 'secprd2014', 'secprd2015', 'secprd2016', 'secprd2017', 'secprd2018', 'secprd2019', 'secprd2020', 'secprd2021', 'secprd2022', 'secprd2023', 'secprd2024', 'secprd2025', 'securd', 'securd1', 'security', 'security_name', 'security_price', 'std_option_price_2002', 'std_option_price_2003', 'std_option_price_2004', 'std_option_price_2005', 'std_option_price_2006', 'std_option_price_2007', 'std_option_price_2008', 'std_option_price_2009', 'std_option_price_2010', 'std_option_price_2011', 'std_option_price_2012', 'std_option_price_2013', 'std_option_price_2014', 'std_option_price_2015', 'std_option_price_2016', 'std_option_price_2017', 'std_option_price_2018', 'std_option_price_2019', 'std_option_price_2020', 'std_option_price_2021', 'std_option_price_2022', 'std_option_price_2023', 'std_option_price_view', 'stdbrte1996', 'stdbrte1997', 'stdbrte1998', 'stdbrte1999', 'stdbrte2000', 'stdbrte2001', 'stdbrte2002', 'stdbrte2003', 'stdbrte2004', 'stdbrte2005', 'stdbrte2006', 'stdbrte2007', 'stdbrte2008', 'stdbrte2009', 'stdbrte2010', 'stdbrte2011', 'stdbrte2012', 'stdbrte2013', 'stdbrte2014', 'stdbrte2015', 'stdbrte2016', 'stdbrte2017', 'stdbrte2018', 'stdbrte2019', 'stdbrte2020', 'stdbrte2021', 'stdbrte2022', 'stdbrte2023', 'stdbrte2024', 'stdbrte2025', 'stdopd1996', 'stdopd1997', 'stdopd1998', 'stdopd1999', 'stdopd2000', 'stdopd2001', 'stdopd2002', 'stdopd2003', 'stdopd2004', 'stdopd2005', 'stdopd2006', 'stdopd2007', 'stdopd2008', 'stdopd2009', 'stdopd2010', 'stdopd2011', 'stdopd2012', 'stdopd2013', 'stdopd2014', 'stdopd2015', 'stdopd2016', 'stdopd2017', 'stdopd2018', 'stdopd2019', 'stdopd2020', 'stdopd2021', 'stdopd2022', 'stdopd2023', 'stdopd2024', 'stdopd2025', 'tick_option_price_2006', 'tick_option_price_2007', 'tick_option_price_2008', 'tick_option_price_2009', 'tick_option_price_2010', 'tick_option_price_2011', 'tick_option_price_2012', 'tick_option_price_2013', 'tick_option_price_2014', 'tick_option_price_2015', 'tick_option_price_2016', 'tick_option_price_2017', 'tick_option_price_2018', 'tick_option_price_2019', 'tick_option_price_2020', 'tick_option_price_2021', 'tick_option_price_2022', 'tick_option_price_2023', 'tick_option_price_view', 'tick_std_option_price_2006', 'tick_std_option_price_2007', 'tick_std_option_price_2008', 'tick_std_option_price_2009', 'tick_std_option_price_2010', 'tick_std_option_price_2011', 'tick_std_option_price_2012', 'tick_std_option_price_2013', 'tick_std_option_price_2014', 'tick_std_option_price_2015', 'tick_std_option_price_2016', 'tick_std_option_price_2017', 'tick_std_option_price_2018', 'tick_std_option_price_2019', 'tick_std_option_price_2020', 'tick_std_option_price_2021', 'tick_std_option_price_2022', 'tick_std_option_price_2023', 'tick_std_option_price_view', 'tick_volatility_surface_2006', 'tick_volatility_surface_2007', 'tick_volatility_surface_2008', 'tick_volatility_surface_2009', 'tick_volatility_surface_2010', 'tick_volatility_surface_2011', 'tick_volatility_surface_2012', 'tick_volatility_surface_2013', 'tick_volatility_surface_2014', 'tick_volatility_surface_2015', 'tick_volatility_surface_2016', 'tick_volatility_surface_2017', 'tick_volatility_surface_2018', 'tick_volatility_surface_2019', 'tick_volatility_surface_2020', 'tick_volatility_surface_2021', 'tick_volatility_surface_2022', 'tick_volatility_surface_2023', 'tick_volatility_surface_view', 'ticker', 'volatility_surface_2002', 'volatility_surface_2003', 'volatility_surface_2004', 'volatility_surface_2005', 'volatility_surface_2006', 'volatility_surface_2007', 'volatility_surface_2008', 'volatility_surface_2009', 'volatility_surface_2010', 'volatility_surface_2011', 'volatility_surface_2012', 'volatility_surface_2013', 'volatility_surface_2014', 'volatility_surface_2015', 'volatility_surface_2016', 'volatility_surface_2017', 'volatility_surface_2018', 'volatility_surface_2019', 'volatility_surface_2020', 'volatility_surface_2021', 'volatility_surface_2022', 'volatility_surface_2023', 'volatility_surface_view', 'vsurfd1996', 'vsurfd1997', 'vsurfd1998', 'vsurfd1999', 'vsurfd2000', 'vsurfd2001', 'vsurfd2002', 'vsurfd2003', 'vsurfd2004', 'vsurfd2005', 'vsurfd2006', 'vsurfd2007', 'vsurfd2008', 'vsurfd2009', 'vsurfd2010', 'vsurfd2011', 'vsurfd2012', 'vsurfd2013', 'vsurfd2014', 'vsurfd2015', 'vsurfd2016', 'vsurfd2017', 'vsurfd2018', 'vsurfd2019', 'vsurfd2020', 'vsurfd2021', 'vsurfd2022', 'vsurfd2023', 'vsurfd2024', 'vsurfd2025', 'zero_curve', 'zerocd']

In [4]:
SECURITY_ID = 108105
SECURITY_NAME = "SPX" # S&P 500 Index

START_DATE = "2025-08-18"
END_DATE = "2025-08-20"

DAYS_TO_EXPIRY_MIN = 30
DAYS_TO_EXPIRY_MAX = 60

# Data Filtering Parameters

MAX_SPREAD_PCT = 0.1 # Maximum spread allowed as % of mid price
MIN_VOLUME = 1000 # Minimum volume required for the option to be considered
MIN_IMPLIED_VOLATILITY = 0.1 # Minimum implied volatility required for the option to be considered
MAX_IMPLIED_VOLATILITY = 0.5 # Maximum implied volatility required for the option to be considered
MIN_OPTION_PRICE = 0.01 # Minimum option price required for the option to be considered
MAX_MONEYNESS = 1 # Maximum moneyness required for the option to be considered (log-moneyness = ln(strike/spot))

# Output Parameters
OUTPUT_DIR = 'data/options_metrics_raw'
SAVE_CSV = True
SAVE_PLOT = True
SAVE_SUMMARY = True

In [5]:
option_query = f"""
SELECT
    date, exdate, strike_price/1000 as strike_price,
    impl_volatility, best_bid, best_offer,
    cp_flag, volume, open_interest,
    delta, gamma, theta, vega
FROM optionm.opprcd2025
WHERE secid = {SECURITY_ID}
    AND date BETWEEN '{START_DATE}' AND '{END_DATE}'
    AND (exdate - date) BETWEEN {DAYS_TO_EXPIRY_MIN} AND {DAYS_TO_EXPIRY_MAX}
    AND volume >= {MIN_VOLUME}
    AND impl_volatility BETWEEN {MIN_IMPLIED_VOLATILITY} AND {MAX_IMPLIED_VOLATILITY}
"""

options_data = db.raw_sql(option_query)
options_data.head()

,date,exdate,strike_price,impl_volatility,best_bid,best_offer,cp_flag,volume,open_interest,delta,gamma,theta,vega
0,2025-08-18,2025-09-19,6450.0,0.119781,101.2,101.7,C,1516.0,22263.0,0.547054,0.001759,-672.336,744.2731
1,2025-08-18,2025-09-19,6460.0,0.118275,94.8,95.4,C,1581.0,2725.0,0.52964,0.001789,-663.3961,747.44
2,2025-08-18,2025-09-19,6465.0,0.117538,91.7,92.3,C,4734.0,3687.0,0.520752,0.001803,-658.5584,748.5036
3,2025-08-18,2025-09-19,6470.0,0.116875,88.7,89.3,C,2686.0,5656.0,0.51175,0.001815,-653.7554,749.2008
4,2025-08-18,2025-09-19,6475.0,0.116154,85.7,86.3,C,1719.0,9580.0,0.50264,0.001827,-648.3953,749.5173

In [6]:
rate_query = f"""
SELECT *
FROM optionm.zerocd
WHERE date BETWEEN '{START_DATE}' AND '{END_DATE}'
    AND days BETWEEN {DAYS_TO_EXPIRY_MIN} AND {DAYS_TO_EXPIRY_MAX}
"""
rate_data = db.raw_sql(rate_query)
rate_data.head()

         date  days      rate
0  2025-08-18  30.0  4.737787
1  2025-08-18  60.0  4.675686
2  2025-08-19  30.0  4.737034
3  2025-08-19  60.0  4.674813
4  2025-08-20  30.0  4.722409

In [7]:
spot_query = f"""
SELECT date, close as spot_price
FROM optionm.secprd2025
WHERE secid = {SECURITY_ID}
    AND date BETWEEN '{START_DATE}' AND '{END_DATE}'
"""
spot_data = db.raw_sql(spot_query)
spot_data.head()

         date  spot_price
0  2025-08-18     6449.15
1  2025-08-19     6411.37
2  2025-08-20     6395.78

In [8]:
db.close()

In [9]:
df = options_data.merge(spot_data, on='date', how='left')
df = df.merge(rate_data, on='date', how='left')

In [10]:
df['mid_price'] = (df['best_bid'] + df['best_offer']) / 2
df['spread'] = (df['best_offer'] - df['best_bid'])
df['spread_pct'] = df['spread'] / df['mid_price']
df['moneyness'] = df['strike_price'] / df['spot_price']
df['date'] = pd.to_datetime(df['date'])
df['exdate'] = pd.to_datetime(df['exdate'])
df['tau (time to maturity)'] = (df['exdate'] - df['date']).dt.days / 365
df_processed = df[
    (df['spread_pct'] <= MAX_SPREAD_PCT) &
    (df['volume'] >= MIN_VOLUME) &
    (df['impl_volatility'] >= MIN_IMPLIED_VOLATILITY) &
    (df['impl_volatility'] <= MAX_IMPLIED_VOLATILITY) &
    (df['moneyness'] <= MAX_MONEYNESS)
]

df_processed.shape

(226, 21)